using Bogus;
using Npgsql;
using NpgsqlTypes;
using Orkyo.Foundation.Seed.Profiles;
using Orkyo.Foundation.Seed.Scales;

namespace Orkyo.Foundation.Seed.Factories;

/// <summary>
/// Seeds sites and spaces.
/// MVP scope: produces non-physical spaces (no floorplan geometry) — keeps the
/// schema CHECK constraint <c>check_physical_has_geometry</c> happy without
/// needing to synthesise polygon coordinates.
/// </summary>
public static class SpaceFactories
{
    public sealed record SeededSite(Guid Id, string Name, string Code);
    public sealed record SeededSpace(Guid Id, Guid SiteId, string Name);
    public sealed record SeededSpaceGroup(Guid Id, string Name);

    public static async Task<IReadOnlyList<SeededSite>> SeedSitesAsync(
        NpgsqlConnection conn, NpgsqlTransaction tx,
        IProfile profile, IScale scale, Faker faker)
    {
        var names = faker.PickRandom(profile.SiteNamePool, scale.Sites).Distinct().ToList();
        // Top up if PickRandom returned fewer unique entries than requested
        // (small pool + high scale.Sites). Append a numeric suffix.
        var idx = 0;
        while (names.Count < scale.Sites)
            names.Add($"{profile.SiteNamePool[idx++ % profile.SiteNamePool.Count]} #{names.Count + 1}");

        var sites = new List<SeededSite>();
        using var writer = await conn.BeginBinaryImportAsync(
            "COPY public.sites (id, name, code, description, created_at, updated_at) FROM STDIN (FORMAT BINARY)");
        _ = tx;

        var now = DateTime.UtcNow;
        foreach (var name in names)
        {
            var id = Guid.NewGuid();
            var code = Slug(name);
            var description = $"{profile.DisplayName} site — generated by seeder.";

            await writer.StartRowAsync();
            await writer.WriteAsync(id, NpgsqlDbType.Uuid);
            await writer.WriteAsync(name, NpgsqlDbType.Varchar);
            await writer.WriteAsync(code, NpgsqlDbType.Varchar);
            await writer.WriteAsync(description, NpgsqlDbType.Text);
            await writer.WriteAsync(now, NpgsqlDbType.TimestampTz);
            await writer.WriteAsync(now, NpgsqlDbType.TimestampTz);

            sites.Add(new SeededSite(id, name, code));
        }
        await writer.CompleteAsync();
        return sites;
    }

    public static async Task<Guid> ResolveSpaceResourceTypeIdAsync(
        NpgsqlConnection conn, NpgsqlTransaction tx)
    {
        await using var cmd = new NpgsqlCommand(
            "SELECT id FROM public.resource_types WHERE key = 'space' LIMIT 1", conn, tx);
        var id = (Guid?)await cmd.ExecuteScalarAsync();
        return id ?? throw new InvalidOperationException(
            "resource_types row with key='space' not found. Has the tenant DB been migrated?");
    }

    public static async Task<IReadOnlyList<SeededSpace>> SeedSpacesAsync(
        NpgsqlConnection conn, NpgsqlTransaction tx,
        IProfile profile, IScale scale, Faker faker,
        IReadOnlyList<SeededSite> sites,
        Guid spaceResourceTypeId)
    {
        if (sites.Count == 0) return Array.Empty<SeededSpace>();

        var seeded = new List<SeededSpace>(sites.Count * scale.SpacesPerSite);
        var now = DateTime.UtcNow;

        // Spaces share their UUID with resources — insert resources first.
        using (var resourceWriter = await conn.BeginBinaryImportAsync(
            "COPY public.resources (id, resource_type_id, name, allocation_mode, base_availability_percent, is_active, created_at, updated_at) " +
            "FROM STDIN (FORMAT BINARY)"))
        {
            foreach (var site in sites)
            {
                for (var i = 1; i <= scale.SpacesPerSite; i++)
                {
                    var id = Guid.NewGuid();
                    var name = string.Format(profile.SpaceNameTemplate, i);
                    await resourceWriter.StartRowAsync();
                    await resourceWriter.WriteAsync(id, NpgsqlDbType.Uuid);
                    await resourceWriter.WriteAsync(spaceResourceTypeId, NpgsqlDbType.Uuid);
                    await resourceWriter.WriteAsync(name, NpgsqlDbType.Varchar);
                    await resourceWriter.WriteAsync("Exclusive", NpgsqlDbType.Varchar);
                    await resourceWriter.WriteAsync(100, NpgsqlDbType.Integer);
                    await resourceWriter.WriteAsync(true, NpgsqlDbType.Boolean);
                    await resourceWriter.WriteAsync(now, NpgsqlDbType.TimestampTz);
                    await resourceWriter.WriteAsync(now, NpgsqlDbType.TimestampTz);
                    seeded.Add(new SeededSpace(id, site.Id, name));
                }
            }
            await resourceWriter.CompleteAsync();
        }

        // Now insert the spaces subtype rows (no name — that's on resources).
        using (var spaceWriter = await conn.BeginBinaryImportAsync(
            "COPY public.spaces (id, site_id, code, is_physical, properties, capacity, created_at, updated_at) " +
            "FROM STDIN (FORMAT BINARY)"))
        {
            _ = tx;
            var idx = 0;
            foreach (var site in sites)
            {
                for (var i = 1; i <= scale.SpacesPerSite; i++)
                {
                    var space = seeded[idx++];
                    var code = $"{site.Code}-{i:D3}";
                    var capacity = faker.PickRandom(new[] { 1, 1, 1, 2, 4, 6, 8, 12, 20 });

                    await spaceWriter.StartRowAsync();
                    await spaceWriter.WriteAsync(space.Id, NpgsqlDbType.Uuid);
                    await spaceWriter.WriteAsync(site.Id, NpgsqlDbType.Uuid);
                    await spaceWriter.WriteAsync(code, NpgsqlDbType.Varchar);
                    await spaceWriter.WriteAsync(false, NpgsqlDbType.Boolean);      // is_physical
                    await spaceWriter.WriteAsync("{}", NpgsqlDbType.Jsonb);          // properties
                    await spaceWriter.WriteAsync(capacity, NpgsqlDbType.Integer);
                    await spaceWriter.WriteAsync(now, NpgsqlDbType.TimestampTz);
                    await spaceWriter.WriteAsync(now, NpgsqlDbType.TimestampTz);
                }
            }
            await spaceWriter.CompleteAsync();
        }

        return seeded;
    }

    /// <summary>
    /// Seeds space groups — <c>resource_groups</c> rows typed to the space resource
    /// type. Mirrors <see cref="PeopleFactories.SeedPersonGroupsAsync"/>; the group
    /// model is shared and discriminated by <c>resource_type_id</c>.
    /// </summary>
    public static async Task<IReadOnlyList<SeededSpaceGroup>> SeedSpaceGroupsAsync(
        NpgsqlConnection conn, NpgsqlTransaction tx,
        IProfile profile, IScale scale, Faker faker,
        Guid spaceResourceTypeId)
    {
        var pool = profile.ResourceGroupPool;
        var names = new List<string>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        for (var i = 0; names.Count < scale.ResourceGroups && i < scale.ResourceGroups * 5; i++)
        {
            var baseName = pool[i % pool.Count];
            var candidate = i < pool.Count ? baseName : $"{baseName} {i / pool.Count + 1}";
            if (seen.Add(candidate)) names.Add(candidate);
        }

        var seeded = new List<SeededSpaceGroup>(names.Count);
        var now = DateTime.UtcNow;
        _ = tx;
        using var writer = await conn.BeginBinaryImportAsync(
            "COPY public.resource_groups (id, name, description, color, display_order, resource_type_id, created_at, updated_at) " +
            "FROM STDIN (FORMAT BINARY)");

        for (var i = 0; i < names.Count; i++)
        {
            var id = Guid.NewGuid();
            await writer.StartRowAsync();
            await writer.WriteAsync(id, NpgsqlDbType.Uuid);
            await writer.WriteAsync(names[i], NpgsqlDbType.Varchar);
            await writer.WriteNullAsync();                               // description
            await writer.WriteNullAsync();                               // color
            await writer.WriteAsync(i, NpgsqlDbType.Integer);           // display_order
            await writer.WriteAsync(spaceResourceTypeId, NpgsqlDbType.Uuid);
            await writer.WriteAsync(now, NpgsqlDbType.TimestampTz);
            await writer.WriteAsync(now, NpgsqlDbType.TimestampTz);
            seeded.Add(new SeededSpaceGroup(id, names[i]));
        }
        await writer.CompleteAsync();
        _ = faker;
        return seeded;
    }

    /// <summary>
    /// Assigns each space to exactly one space group (round-robin). A space may belong to at most
    /// one group (enforce_space_single_group trigger, migration 1530). A space's
    /// <see cref="SeededSpace.Id"/> is its resource id (spaces share the UUID).
    /// </summary>
    public static async Task<int> SeedSpaceGroupMembersAsync(
        NpgsqlConnection conn, NpgsqlTransaction tx,
        Faker faker,
        IReadOnlyList<SeededSpace> spaces,
        IReadOnlyList<SeededSpaceGroup> groups,
        Guid spaceResourceTypeId)
    {
        if (groups.Count == 0 || spaces.Count == 0) return 0;

        // A space may belong to at most ONE group — enforced by the
        // enforce_space_single_group() trigger (migration 1530). One round-robin group each.
        var memberships = new List<(Guid GroupId, Guid ResourceId)>(spaces.Count);
        for (var i = 0; i < spaces.Count; i++)
            memberships.Add((groups[i % groups.Count].Id, spaces[i].Id));

        _ = tx;
        _ = faker;
        using var writer = await conn.BeginBinaryImportAsync(
            "COPY public.resource_group_members (resource_group_id, resource_id, resource_type_id) " +
            "FROM STDIN (FORMAT BINARY)");

        foreach (var (groupId, resourceId) in memberships)
        {
            await writer.StartRowAsync();
            await writer.WriteAsync(groupId, NpgsqlDbType.Uuid);
            await writer.WriteAsync(resourceId, NpgsqlDbType.Uuid);
            await writer.WriteAsync(spaceResourceTypeId, NpgsqlDbType.Uuid);
        }
        await writer.CompleteAsync();
        return memberships.Count;
    }

    private static string Slug(string s)
    {
        var lower = s.ToLowerInvariant();
        var chars = lower.Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray();
        var slug = new string(chars).Trim('-');
        while (slug.Contains("--")) slug = slug.Replace("--", "-");
        return slug.Length > 60 ? slug[..60] : slug;
    }
}
