using System.Runtime.CompilerServices;
using System.Text.Json;

namespace Orkyo.Foundation.Tests.Contracts;

/// <summary>
/// Snapshot test: the live OpenAPI spec generated by the foundation web layer must
/// match the committed snapshot at frontend/contracts/openapi.json.
///
/// On first run (no snapshot yet): creates the snapshot file and passes — commit it.
/// On subsequent runs: fails with a diff if the spec has changed.
///
/// When you change a backend endpoint shape, the workflow is:
///   1. Delete openapi.json (or run with UPDATE_OPENAPI_SNAPSHOT=1 env var).
///   2. Re-run this test — it regenerates the snapshot.
///   3. Run `npm run generate:types` in foundation/frontend.
///   4. Commit both openapi.json and the updated generated types.
/// </summary>
[Collection("Database collection")]
public sealed class OpenApiContractTest(DatabaseFixture fixture)
{
    [Fact]
    public async Task OpenApiSpec_MatchesCommittedSnapshot()
    {
        var client = fixture.Factory.CreateClient();
        var response = await client.GetAsync("/openapi/v1.json");
        response.EnsureSuccessStatusCode();

        var rawJson = await response.Content.ReadAsStringAsync();

        // Normalise: re-parse + re-serialise with deterministic indentation so
        // whitespace differences never cause spurious failures.
        var normalised = NormaliseJson(rawJson);

        var snapshotPath = ResolveSnapshotPath();
        var update = Environment.GetEnvironmentVariable("UPDATE_OPENAPI_SNAPSHOT") == "1";

        if (!File.Exists(snapshotPath) || update)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(snapshotPath)!);
            await File.WriteAllTextAsync(snapshotPath, normalised);

            // First bootstrap: pass so the developer can commit the snapshot.
            // In CI this will leave an uncommitted file; the pipeline's git-diff
            // check will catch it.
            return;
        }

        var expected = NormaliseJson(await File.ReadAllTextAsync(snapshotPath));

        normalised.Should().Be(expected,
            "the live OpenAPI spec has diverged from the committed snapshot at " +
            $"{snapshotPath}. Delete the snapshot (or set UPDATE_OPENAPI_SNAPSHOT=1) " +
            "and re-run the test to regenerate it, then run 'npm run generate:types' " +
            "in foundation/frontend and commit both files.");
    }

    private static string NormaliseJson(string json)
    {
        using var doc = JsonDocument.Parse(json);
        return JsonSerializer.Serialize(doc.RootElement,
            new JsonSerializerOptions { WriteIndented = true });
    }

    // Resolves to orkyo-foundation/frontend/contracts/openapi.json regardless of
    // where the test binary is, using the source file's compile-time path.
    private static string ResolveSnapshotPath([CallerFilePath] string thisFile = "")
    {
        // thisFile = …/orkyo-foundation/backend/tests/Contracts/OpenApiContractTest.cs
        // Go up 3 dirs → orkyo-foundation/, then into frontend/contracts/
        var foundationRoot = Path.GetFullPath(
            Path.Combine(Path.GetDirectoryName(thisFile)!, "..", "..", ".."));
        return Path.Combine(foundationRoot, "frontend", "contracts", "openapi.json");
    }
}
